### ISSUE TITLE
Not working with msbuild standalone

### ISSUE THREAD

**Issue by GravityTraveler** [carstenschaefer/FolderSecurityViewer#1]
For me, I get this constant error compiling using msbuild standalone:
MSB4041: The default XML namespace of the project must be the MSBuild XML namespace.

I am using the latest msbuild that comes with .Net SDK.

**Comment by matzefriedrich** [comment]
If the behavior relates to errors like `Your project file doesn't list 'win' as a "RuntimeIdentifier." You should add 'win' to the "RuntimeIdentifiers" property in your project file and then re-run NuGet restore.` you can try to rerun the build as follows:

````sh
$ cd sourcecodes
$ msbuild FolderSecurityViewer.sln /t:restore
````
Sometimes, the MSBuild environment struggles with files already converted to the new project file flavor. I could reproduce the error on a clean checkout of the repo; running `msbuild` without explicitly requesting the restore of NuGet packages causes the build to fail. On the other hand, building the solution via Visual Studio 2022 was successful on the first attempt.
